version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:7.0
    container_name: mern-app-mongo
    restart: unless-stopped
    # ports: 移除端口映射，只在容器内部使用
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app-network

  # 后端服务
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mern-app-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-app-network

  # 前端服务
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mern-app-client
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-app-network

volumes:
  mongo_data:

networks:
  mern-app-network:
    driver: bridge